[project]
name = "zensical-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.0"
dependencies = [
    "typer==0.20.0",
    "zensical==0.0.11",
]
