[project]
site_name = "Zensical Template"
repo_name = "DarkRader/zensical-template"  # change to your own repository name
repo_url = "https://github.com/DarkRader/zensical-template"
edit_uri = "https://github.com/CloudRader/zensical-template/edit/main/docs/"
extra_css = ["assets/stylesheets/extra.css"]

nav = [  # example navifation
    {"Home" =  [
        "index.md",
    ]},
  # {"User Guide" = [
  #   {"Introduction" = [
  #       "user-guide/introduction/index.md",
  #       "user-guide/introduction/about.md",
  #       "user-guide/introduction/why-use.md",
  #   ]},
  #   {"Quickstart" = [
  #       "user-guide/quickstart/index.md",
  #       # "user-guide/quickstart/example.md",
  #   ]},
  #   {"Basic Features" = [
  #       "user-guide/basic-features/index.md",
  #       # "user-guide/basic-features/example.md",
  #   ]},
  #   {"FAQ" = [
  #       "user-guide/faq/index.md"
  #   ]}
  # ]},
  # {"Manager Guide" = [
  #   {"Introduction" = [
  #       "manager-guide/introduction/index.md",
  #   ]},
  # ]},
  # {"Hosting Guide" = [
  #   {"Introduction" = [
  #       "hosting-guide/introduction/index.md",
  #   ]},
  # ]},
  # {"Contribute Guide" = [
  #   {"Introduction" = [
  #       "contribute-guide/introduction/index.md",
  #   ]},
  # ]},
  # {"API Reference" = [
  #   "api-reference/index.md",
  # ]},
  # {"Release Notes" = [
  #   "release-notes/backend.md",
  #   "release-notes/frontend.md",
  # ]},
]

[project.theme]
features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.top",
    "navigation.tracking",
    "navigation.tabs",
    "navigation.prune",
    "navigation.indexes",
    "navigation.footer",

    "content.action.edit",  # Edit this page
    "content.action.view",  # View source of this page
    "content.tooltips",
]
# logo = "assets/example.png"
# favicon = "assets/example.png"

[project.theme.icon]
repo = "fontawesome/brands/github" # you can change this to any other icon from fontawesome

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "default"
# primary = "indigo"  # set prefer colors
# accent = "yellow"
toggle.icon = "material/weather-sunny"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "slate"
# primary = "indigo"  # set prefer colors
# accent = "yellow"
toggle.icon = "material/weather-night"
toggle.name = "Switch to dark mode"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
